Support konsole, support empty username
jsimonetti/ssh-scheme-handler pull request #2
Opened 2021-10-28 13:07 UTC by Ashark

2021-10-28 13:35 UTC, jsimonetti requested changes
If you could also sign off on your commit, the rest seems good to me!
Thank you for your contribution!

2021-10-28 13:35 UTC, jsimonetti commented on main.go
> +	print("Running ", prog, " ")
Could you remove these two statements? I assume they are only used for debugging right?

2021-10-28 13:42 UTC, Ashark commented on main.go
> +	print("Running ", prog, " ")
Yes, I used for debugging, trying to understand why ssh command did not work.
Are you sure you want to remove that? I think it may be useful. And it is not visible in "normal use", when the handler is invoked.

2021-10-29 06:44 UTC, jsimonetti commented on main.go
> +	print("Running ", prog, " ")
While I agree it is not normally visible, these commands are executed by your window manager. I honestly have no idea what impact stdout output would have. I have not read the spec about this. So, just to be safe, let's remove it.

2021-10-29 11:04 UTC, merged

2021-10-29 11:04 UTC, jsimonetti commented
Awesome. Thanks!